/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Radioemisora.RadioEmisora;
import Model.Disco.Disco;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author fabia
 */
public class InformacionDisc extends javax.swing.JFrame {
    Disco disco;
    RadioEmisora emisora;
    DefaultComboBoxModel comboBoxModel;
    DefaultListModel listaDiscosModel;
    /**
     * Creates new form InformacionDisc
     */
    public InformacionDisc(Disco disco, DefaultComboBoxModel comboDiscos, DefaultListModel listaDiscos, RadioEmisora emisora) {
        this.disco = disco;
        this.emisora = emisora;
        this.comboBoxModel = comboDiscos;
        this.listaDiscosModel = listaDiscos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizarBoton = new javax.swing.JButton();
        nombreDiscoInput = new javax.swing.JTextField();
        cantanteDiscoInput = new javax.swing.JTextField();
        generoDiscoInput = new javax.swing.JTextField();
        anioDiscoInput = new javax.swing.JTextField();
        ubicacionDiscoInput = new javax.swing.JTextField();
        imagenDiscoInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actualizarBoton.setText("Actualizar Informacion");
        actualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBotonActionPerformed(evt);
            }
        });

        nombreDiscoInput.setText(this.disco.getNombre());
        nombreDiscoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDiscoInputActionPerformed(evt);
            }
        });

        cantanteDiscoInput.setText(this.disco.getCantante());

        generoDiscoInput.setText(this.disco.getGenero());

        anioDiscoInput.setText(Integer.toString(this.disco.getAño())
        );
        anioDiscoInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioDiscoInputKeyTyped(evt);
            }
        });

        ubicacionDiscoInput.setText(this.disco.getUbicacionFisica());

        imagenDiscoInput.setText(this.disco.getImagen());

        jLabel1.setText("Nombre:");

        jLabel2.setText("Cantante: ");

        jLabel3.setText("Genero: ");

        jLabel4.setText("Año: ");

        jLabel5.setText("Ubicación: ");

        jLabel6.setText("Imagen: ");

        jLabel7.setText("Informacion del disco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualizarBoton)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantanteDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubicacionDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anioDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantanteDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(generoDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(anioDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ubicacionDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(imagenDiscoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(actualizarBoton)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBotonActionPerformed
        String nombre = this.nombreDiscoInput.getText();
        String cantante = this.cantanteDiscoInput.getText();
        String genero = this.generoDiscoInput.getText();
        String anioStr = this.anioDiscoInput.getText();
        String ubicacion = this.ubicacionDiscoInput.getText();
        String imagen = this.imagenDiscoInput.getText();
        
        if(nombre.isEmpty() || cantante.isEmpty() || genero.isEmpty() || anioStr.isEmpty() ||
                ubicacion.isEmpty() || imagen.isEmpty()){
            JOptionPane.showMessageDialog(this, "Datos incorrectos...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        this.comboBoxModel.removeElement(disco.toString());
        this.listaDiscosModel.removeElement(disco.toString());
        int anio = Integer.parseInt(anioStr);
        this.disco.setNombre(nombre);
        this.disco.setCantante(cantante);
        this.disco.setGenero(genero);
        this.disco.setAño(anio);
        this.disco.setUbicacionFisica(ubicacion);
        this.disco.setImagen(imagen);

        this.comboBoxModel.addElement(disco.toString());
        this.listaDiscosModel.addElement(disco.toString());
        this.dispose();
    }//GEN-LAST:event_actualizarBotonActionPerformed

    private void nombreDiscoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDiscoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDiscoInputActionPerformed

    private void anioDiscoInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioDiscoInputKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_anioDiscoInputKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBoton;
    private javax.swing.JTextField anioDiscoInput;
    private javax.swing.JTextField cantanteDiscoInput;
    private javax.swing.JTextField generoDiscoInput;
    private javax.swing.JTextField imagenDiscoInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreDiscoInput;
    private javax.swing.JTextField ubicacionDiscoInput;
    // End of variables declaration//GEN-END:variables
}
