/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Radioemisora.RadioEmisora;
import Model.Locutor.Locutor;
import Model.Programa.Programa;
import Model.Disco.Disco;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author kenne
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private RadioEmisora emisora;
    private DefaultListModel locutoresListModel = new DefaultListModel();
    private DefaultListModel programasListModel = new DefaultListModel();
    private DefaultListModel discosListModel = new DefaultListModel();
    private DefaultComboBoxModel locutoresComboBoxModel = new DefaultComboBoxModel();
    private DefaultComboBoxModel locutoresProgramasComboBoxModel = new DefaultComboBoxModel();
    private DefaultComboBoxModel programasComboBoxModel = new DefaultComboBoxModel();
    private DefaultComboBoxModel discoComboBoxModel = new DefaultComboBoxModel();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(RadioEmisora pEmisora) {
        initComponents();
        emisora = pEmisora;
        this.programasLocutoresCombo.setModel(this.locutoresProgramasComboBoxModel);
        this.programasListaProgramasBox.setModel(this.programasListModel);
        this.programasListaCombo.setModel(this.programasComboBoxModel);
        this.listaDiscoComboBox.setModel(this.discoComboBoxModel);
        this.discosListaBox.setModel(this.discosListModel);
        

        // Desabiliatr tabs
        this.toggleWindowTabs(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jColorChooser1 = new javax.swing.JColorChooser();
        windowTabs = new javax.swing.JTabbedPane();
        radioEmisoraTab = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        frecuenciaLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        direccionFisicaLabel = new javax.swing.JLabel();
        nombreEmisoraShow = new javax.swing.JLabel();
        frecuenciaEmisoraShow = new javax.swing.JLabel();
        urlEmisoraShow = new javax.swing.JLabel();
        direccionFisicaEmisoraShow = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nuevoNombreLabel = new javax.swing.JLabel();
        nuevaFrecuenciaLabel = new javax.swing.JLabel();
        nuevoUrlLabel = new javax.swing.JLabel();
        nuevaDireccionFisicaLabel = new javax.swing.JLabel();
        nombreEmisoraInput = new javax.swing.JTextField();
        frecuenciaEmisoraInput = new javax.swing.JTextField();
        urlEmisoraInput = new javax.swing.JTextField();
        direccionFisicaInput = new javax.swing.JTextField();
        btnActualizarEmisora = new javax.swing.JButton();
        locutoresTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLocutoresBox = new javax.swing.JList<>();
        nuevoLocutorLabel = new javax.swing.JLabel();
        listaLocutoresLabel = new javax.swing.JLabel();
        IdLocutorLabel = new javax.swing.JLabel();
        nombreLocutorLabel = new javax.swing.JLabel();
        correoLocutorLabel = new javax.swing.JLabel();
        telefonoLocutorLabel = new javax.swing.JLabel();
        direccionLocutorLabel = new javax.swing.JLabel();
        sexoLocutorLabel = new javax.swing.JLabel();
        fechaLocutorLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        locutorNombreInput = new javax.swing.JTextField();
        locutorIdInput = new javax.swing.JTextField();
        locutorCorreoInput = new javax.swing.JTextField();
        locutorTelefonoInput = new javax.swing.JTextField();
        locutorDireccionInput = new javax.swing.JTextField();
        locutorSexoInput = new javax.swing.JTextField();
        locutorFechaInput = new javax.swing.JTextField();
        botonAgregarLocutor = new javax.swing.JButton();
        actualizarLocutorLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        locutoresActualizarCombo = new javax.swing.JComboBox<>();
        botonVerInfoLocutor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        programasTab = new javax.swing.JPanel();
        nuevoProgramaLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        programaNombreLabel = new javax.swing.JLabel();
        programaHorarioLabel = new javax.swing.JLabel();
        programasDuracionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        programaNombreInput = new javax.swing.JTextField();
        programaHorarioInput = new javax.swing.JTextField();
        programaDuracionInput = new javax.swing.JTextField();
        programasGeneroInput = new javax.swing.JTextField();
        botonCrearNuevoPrograma = new javax.swing.JButton();
        programasListaCombo = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        programaAsignarLocutorLabel = new javax.swing.JLabel();
        programasLocutoresCombo = new javax.swing.JComboBox<>();
        botonAsignarLocutor = new javax.swing.JButton();
        programasListaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        programasListaProgramasBox = new javax.swing.JList<>();
        programaAsignarPlaylistLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        programasListaCombo2 = new javax.swing.JComboBox<>();
        programasPlaylistsCombo = new javax.swing.JComboBox<>();
        botonAsignarPlaylist = new javax.swing.JButton();
        playlistsTab = new javax.swing.JPanel();
        nuevaPlaylistLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        playlistNombre = new javax.swing.JLabel();
        playlistsGeneroLabel = new javax.swing.JLabel();
        playlistNombreInput = new javax.swing.JTextField();
        playlistGeneroInput = new javax.swing.JTextField();
        botonAgregarPlaylist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        playlistsListaPlaylistsBox = new javax.swing.JList<>();
        listaPlaylistsLabel = new javax.swing.JLabel();
        verCancionesPlaylistLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        playlistsCombo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        playlistsListaCancionesBox = new javax.swing.JList<>();
        cancionesTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        discosTab = new javax.swing.JPanel();
        discoNombreLabel = new javax.swing.JLabel();
        nombreDiscoTextField = new javax.swing.JTextField();
        cantanteDiscoTextField = new javax.swing.JTextField();
        cantanteDiscoLabel = new javax.swing.JLabel();
        generoDiscoLabel = new javax.swing.JLabel();
        generoDiscoTextField = new javax.swing.JTextField();
        anioDiscoLabel = new javax.swing.JLabel();
        anioDiscoTextField = new javax.swing.JTextField();
        ubicacionDiscoLabel = new javax.swing.JLabel();
        ubicacionDiscoTextField = new javax.swing.JTextField();
        imagenDiscoTextField = new javax.swing.JTextField();
        imagenDiscoLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        discosListaBox = new javax.swing.JList<>();
        listaDiscoComboBox = new javax.swing.JComboBox<>();
        botonCrearDisco = new javax.swing.JButton();
        botonVerDisco = new javax.swing.JButton();
        listaDiscosLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLabel.setText("Nombre:");

        frecuenciaLabel.setText("Frecuencia:");

        urlLabel.setText("URL:");

        direccionFisicaLabel.setText("Dirección Física:");

        nombreEmisoraShow.setText("INDEFINIDO");

        frecuenciaEmisoraShow.setText("INDEFINIDO");

        urlEmisoraShow.setText("INDEFINIDO");

        direccionFisicaEmisoraShow.setText("INDEFINIDO");

        nuevoNombreLabel.setText("Nuevo Nombre:");

        nuevaFrecuenciaLabel.setText("Nueva Frecuencia:");

        nuevoUrlLabel.setText("Nuevo URL:");

        nuevaDireccionFisicaLabel.setText("Nueva Dirección Física:");

        nombreEmisoraInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEmisoraInputActionPerformed(evt);
            }
        });

        urlEmisoraInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlEmisoraInputActionPerformed(evt);
            }
        });

        direccionFisicaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionFisicaInputActionPerformed(evt);
            }
        });

        btnActualizarEmisora.setText("Actualizar Información");
        btnActualizarEmisora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmisoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioEmisoraTabLayout = new javax.swing.GroupLayout(radioEmisoraTab);
        radioEmisoraTab.setLayout(radioEmisoraTabLayout);
        radioEmisoraTabLayout.setHorizontalGroup(
            radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(radioEmisoraTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarEmisora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(radioEmisoraTabLayout.createSequentialGroup()
                        .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(frecuenciaLabel)
                            .addComponent(urlLabel)
                            .addComponent(direccionFisicaLabel))
                        .addGap(60, 60, 60)
                        .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionFisicaEmisoraShow)
                            .addComponent(urlEmisoraShow)
                            .addComponent(frecuenciaEmisoraShow)
                            .addComponent(nombreEmisoraShow))
                        .addGap(0, 443, Short.MAX_VALUE))
                    .addGroup(radioEmisoraTabLayout.createSequentialGroup()
                        .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevaDireccionFisicaLabel)
                            .addComponent(nuevoUrlLabel)
                            .addComponent(nuevaFrecuenciaLabel)
                            .addComponent(nuevoNombreLabel))
                        .addGap(25, 25, 25)
                        .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreEmisoraInput)
                            .addComponent(frecuenciaEmisoraInput)
                            .addComponent(urlEmisoraInput)
                            .addComponent(direccionFisicaInput))))
                .addContainerGap())
        );
        radioEmisoraTabLayout.setVerticalGroup(
            radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioEmisoraTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreEmisoraShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frecuenciaLabel)
                    .addComponent(frecuenciaEmisoraShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlEmisoraShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionFisicaLabel)
                    .addComponent(direccionFisicaEmisoraShow))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoNombreLabel)
                    .addComponent(nombreEmisoraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaFrecuenciaLabel)
                    .addComponent(frecuenciaEmisoraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoUrlLabel)
                    .addComponent(urlEmisoraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(radioEmisoraTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaDireccionFisicaLabel)
                    .addComponent(direccionFisicaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActualizarEmisora)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        windowTabs.addTab("RadioEmisora", radioEmisoraTab);

        jScrollPane1.setViewportView(listaLocutoresBox);

        nuevoLocutorLabel.setText("Agregar Nuevo Locutor");

        listaLocutoresLabel.setText("Lista de locutores:");

        IdLocutorLabel.setText("Id:");

        nombreLocutorLabel.setText("Nombre:");

        correoLocutorLabel.setText("Correo:");

        telefonoLocutorLabel.setText("Telefono:");

        direccionLocutorLabel.setText("Dirección:");

        sexoLocutorLabel.setText("Sexo:");

        fechaLocutorLabel.setText("Fecha:");

        locutorNombreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locutorNombreInputActionPerformed(evt);
            }
        });

        locutorCorreoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locutorCorreoInputActionPerformed(evt);
            }
        });

        locutorTelefonoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locutorTelefonoInputActionPerformed(evt);
            }
        });

        botonAgregarLocutor.setText("Agregar Nuevo Locutor");
        botonAgregarLocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarLocutorActionPerformed(evt);
            }
        });

        actualizarLocutorLabel.setText("Actualizar Locutor:");

        locutoresActualizarCombo.setModel(this.locutoresComboBoxModel);
        locutoresActualizarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locutoresActualizarComboActionPerformed(evt);
            }
        });

        botonVerInfoLocutor.setText("Ver Información");
        botonVerInfoLocutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerInfoLocutorMouseClicked(evt);
            }
        });
        botonVerInfoLocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerInfoLocutorActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        javax.swing.GroupLayout locutoresTabLayout = new javax.swing.GroupLayout(locutoresTab);
        locutoresTab.setLayout(locutoresTabLayout);
        locutoresTabLayout.setHorizontalGroup(
            locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locutoresTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, locutoresTabLayout.createSequentialGroup()
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(locutoresTabLayout.createSequentialGroup()
                                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLocutorLabel)
                                    .addComponent(IdLocutorLabel)
                                    .addComponent(correoLocutorLabel)
                                    .addComponent(telefonoLocutorLabel)
                                    .addComponent(direccionLocutorLabel)
                                    .addComponent(sexoLocutorLabel)
                                    .addComponent(fechaLocutorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(locutorNombreInput)
                                    .addComponent(locutorIdInput)
                                    .addComponent(locutorCorreoInput)
                                    .addComponent(locutorTelefonoInput)
                                    .addComponent(locutorDireccionInput)
                                    .addComponent(locutorSexoInput)
                                    .addComponent(locutorFechaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)))
                            .addComponent(botonAgregarLocutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, locutoresTabLayout.createSequentialGroup()
                                .addComponent(nuevoLocutorLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, locutoresTabLayout.createSequentialGroup()
                                .addComponent(locutoresActualizarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVerInfoLocutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaLocutoresLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(locutoresTabLayout.createSequentialGroup()
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualizarLocutorLabel)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        locutoresTabLayout.setVerticalGroup(
            locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locutoresTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoLocutorLabel)
                    .addComponent(listaLocutoresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(locutoresTabLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLocutorLabel)
                            .addComponent(locutorNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdLocutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locutorIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoLocutorLabel)
                            .addComponent(locutorCorreoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoLocutorLabel)
                            .addComponent(locutorTelefonoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionLocutorLabel)
                            .addComponent(locutorDireccionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexoLocutorLabel)
                            .addComponent(locutorSexoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaLocutorLabel)
                            .addComponent(locutorFechaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarLocutor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(actualizarLocutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(locutoresTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVerInfoLocutor)
                    .addComponent(locutoresActualizarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        windowTabs.addTab("Locutores", locutoresTab);

        nuevoProgramaLabel.setText("Agregar Nuevo Programa:");

        programaNombreLabel.setText("Nombre: ");

        programaHorarioLabel.setText("Horario:");

        programasDuracionLabel.setText("Duración:");

        jLabel1.setText("Genero:");

        programaHorarioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programaHorarioInputActionPerformed(evt);
            }
        });

        programaDuracionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programaDuracionInputActionPerformed(evt);
            }
        });
        programaDuracionInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                programaDuracionInputKeyTyped(evt);
            }
        });

        botonCrearNuevoPrograma.setText("Agregar Progama");
        botonCrearNuevoPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearNuevoProgramaActionPerformed(evt);
            }
        });

        programasListaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programasListaComboActionPerformed(evt);
            }
        });

        programaAsignarLocutorLabel.setText("Asignar Locutor a Programa:");

        programasLocutoresCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programasLocutoresComboActionPerformed(evt);
            }
        });

        botonAsignarLocutor.setText("Asignar Locutor");
        botonAsignarLocutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarLocutorActionPerformed(evt);
            }
        });

        programasListaLabel.setText("Lista de Programas:");

        jScrollPane2.setViewportView(programasListaProgramasBox);

        programaAsignarPlaylistLabel.setText("Asignar Playlist a Programa:");

        botonAsignarPlaylist.setText("Asignar Playlist");

        javax.swing.GroupLayout programasTabLayout = new javax.swing.GroupLayout(programasTab);
        programasTab.setLayout(programasTabLayout);
        programasTabLayout.setHorizontalGroup(
            programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(programasTabLayout.createSequentialGroup()
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAsignarLocutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(programasLocutoresCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(programasListaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(programasListaCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(programasPlaylistsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAsignarPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(programasTabLayout.createSequentialGroup()
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nuevoProgramaLabel)
                                    .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonCrearNuevoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(programasTabLayout.createSequentialGroup()
                                            .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(programasTabLayout.createSequentialGroup()
                                                    .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(programaHorarioLabel))
                                                    .addGap(25, 25, 25))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, programasTabLayout.createSequentialGroup()
                                                    .addComponent(programaNombreLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(programaHorarioInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                                    .addComponent(programasGeneroInput))
                                                .addComponent(programaNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(programasTabLayout.createSequentialGroup()
                                .addComponent(programasDuracionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(programaDuracionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(programaAsignarLocutorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programaAsignarPlaylistLabel)
                            .addComponent(programasListaLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programasTabLayout.setVerticalGroup(
            programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoProgramaLabel)
                    .addComponent(programasListaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(programasTabLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programaNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programaNombreLabel))
                        .addGap(18, 18, 18)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programaHorarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programaHorarioLabel))
                        .addGap(18, 18, 18)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programasDuracionLabel)
                            .addComponent(programaDuracionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programasGeneroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addComponent(botonCrearNuevoPrograma)))
                .addGap(28, 28, 28)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programaAsignarLocutorLabel)
                    .addComponent(programaAsignarPlaylistLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(programasListaCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programasListaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programasLocutoresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programasPlaylistsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(programasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAsignarLocutor)
                    .addComponent(botonAsignarPlaylist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        windowTabs.addTab("Programas", programasTab);

        nuevaPlaylistLabel.setText("Agregar Nueva Playlist");

        playlistNombre.setText("Nombre:");

        playlistsGeneroLabel.setText("Genero:");

        playlistNombreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistNombreInputActionPerformed(evt);
            }
        });

        playlistGeneroInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistGeneroInputActionPerformed(evt);
            }
        });

        botonAgregarPlaylist.setText("Agregar Playlist");

        jScrollPane3.setViewportView(playlistsListaPlaylistsBox);

        listaPlaylistsLabel.setText("Lista de Playlists:");

        verCancionesPlaylistLabel.setText("Ver Canciones:");

        playlistsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane4.setViewportView(playlistsListaCancionesBox);

        javax.swing.GroupLayout playlistsTabLayout = new javax.swing.GroupLayout(playlistsTab);
        playlistsTab.setLayout(playlistsTabLayout);
        playlistsTabLayout.setHorizontalGroup(
            playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevaPlaylistLabel)
                    .addComponent(jSeparator5)
                    .addGroup(playlistsTabLayout.createSequentialGroup()
                        .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playlistNombre)
                            .addComponent(playlistsGeneroLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playlistGeneroInput)
                            .addComponent(playlistNombreInput)))
                    .addComponent(botonAgregarPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(verCancionesPlaylistLabel)
                    .addComponent(jSeparator7)
                    .addComponent(playlistsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(playlistsTabLayout.createSequentialGroup()
                        .addComponent(listaPlaylistsLabel)
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
        );
        playlistsTabLayout.setVerticalGroup(
            playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaPlaylistLabel)
                    .addComponent(listaPlaylistsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playlistsTabLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playlistNombre)
                            .addComponent(playlistNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(playlistsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playlistsGeneroLabel)
                            .addComponent(playlistGeneroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregarPlaylist)
                        .addGap(39, 39, 39)
                        .addComponent(verCancionesPlaylistLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playlistsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        windowTabs.addTab("Playlists", playlistsTab);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout cancionesTabLayout = new javax.swing.GroupLayout(cancionesTab);
        cancionesTab.setLayout(cancionesTabLayout);
        cancionesTabLayout.setHorizontalGroup(
            cancionesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(634, Short.MAX_VALUE))
        );
        cancionesTabLayout.setVerticalGroup(
            cancionesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        windowTabs.addTab("Canciones", cancionesTab);

        discoNombreLabel.setText("Nombre:");

        cantanteDiscoLabel.setText("Cantante: ");

        generoDiscoLabel.setText("Genero: ");

        anioDiscoLabel.setText("Año: ");

        anioDiscoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioDiscoTextFieldActionPerformed(evt);
            }
        });
        anioDiscoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioDiscoTextFieldKeyTyped(evt);
            }
        });

        ubicacionDiscoLabel.setText("Ubicacion: ");

        imagenDiscoLabel.setText("Imagen: ");

        jScrollPane5.setViewportView(discosListaBox);

        botonCrearDisco.setText("Crear disco");
        botonCrearDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearDiscoActionPerformed(evt);
            }
        });

        botonVerDisco.setText("Ver informacion");
        botonVerDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDiscoActionPerformed(evt);
            }
        });

        listaDiscosLabel.setText("Lista de discos:");

        jLabel4.setText("Actualizar disco:");

        javax.swing.GroupLayout discosTabLayout = new javax.swing.GroupLayout(discosTab);
        discosTab.setLayout(discosTabLayout);
        discosTabLayout.setHorizontalGroup(
            discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discosTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discosTabLayout.createSequentialGroup()
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discosTabLayout.createSequentialGroup()
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(discosTabLayout.createSequentialGroup()
                                .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ubicacionDiscoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generoDiscoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(discoNombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cantanteDiscoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(anioDiscoLabel))
                                    .addComponent(imagenDiscoLabel))
                                .addGap(27, 27, 27)
                                .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imagenDiscoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(cantanteDiscoTextField)
                                    .addComponent(nombreDiscoTextField)
                                    .addComponent(generoDiscoTextField)
                                    .addComponent(anioDiscoTextField)
                                    .addComponent(ubicacionDiscoTextField)))
                            .addComponent(botonCrearDisco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaDiscosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(discosTabLayout.createSequentialGroup()
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(listaDiscoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(botonVerDisco)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        discosTabLayout.setVerticalGroup(
            discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discosTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(listaDiscosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discosTabLayout.createSequentialGroup()
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discoNombreLabel)
                            .addComponent(nombreDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantanteDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantanteDiscoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generoDiscoLabel)
                            .addComponent(generoDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anioDiscoLabel)
                            .addComponent(anioDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubicacionDiscoLabel)
                            .addComponent(ubicacionDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagenDiscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenDiscoLabel)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(botonCrearDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(discosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaDiscoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerDisco))
                .addGap(24, 24, 24))
        );

        windowTabs.addTab("Disco", discosTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(windowTabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Activa los tabs de las ventas o las desactiva
     *
     * @param activar
     */
    private void toggleWindowTabs(boolean activar) {
        for (int i = 1; i < this.windowTabs.getTabCount(); i++) {
            this.windowTabs.setEnabledAt(i, activar);
        }
    }

    private void nombreEmisoraInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEmisoraInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmisoraInputActionPerformed

    private void urlEmisoraInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlEmisoraInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlEmisoraInputActionPerformed

    private void direccionFisicaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionFisicaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionFisicaInputActionPerformed
    /**
     * Evento para actualizar la informacion de la radio emisora Las ventanillas
     * se abilitaran hasta que la informacion se ingrese
     *
     * @param evt Evento realizado a la hora de presionar el boton
     */
    private void btnActualizarEmisoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmisoraActionPerformed
        String nombre = this.nombreEmisoraInput.getText();
        String url = this.urlEmisoraInput.getText();
        String frecuencia = this.frecuenciaEmisoraInput.getText();
        String direccion = this.direccionFisicaInput.getText();
        if (nombre.isEmpty() || url.isEmpty()
                || frecuencia.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos invalidos...", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            emisora.setNombre(nombre);
            emisora.setFrecuencia(frecuencia);
            emisora.setUrlSitioWeb(url);
            emisora.setDireccionFisica(direccion);

            this.direccionFisicaEmisoraShow.setText(emisora.getDireccionFisica());
            this.frecuenciaEmisoraShow.setText(emisora.getFrecuencia());
            this.nombreEmisoraShow.setText(emisora.getNombre());
            this.urlEmisoraShow.setText(emisora.getUrlSitioWeb());

            this.toggleWindowTabs(true);
             
            this.frecuenciaEmisoraInput.setText("");
            this.direccionFisicaInput.setText("");
            this.nombreEmisoraInput.setText("");
            this.urlEmisoraInput.setText("");
            
            JOptionPane.showMessageDialog(this, "Emisora actualizada...", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarEmisoraActionPerformed

    private void locutorNombreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locutorNombreInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locutorNombreInputActionPerformed

    private void locutorCorreoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locutorCorreoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locutorCorreoInputActionPerformed

    private void locutorTelefonoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locutorTelefonoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locutorTelefonoInputActionPerformed

    /**
     * Realiza la accion para agregar los datos de un locutor nuevo
     * 
     * @param evt Evento realizado a la hora de presionar el boton
     */
    private void botonAgregarLocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarLocutorActionPerformed
        String id = this.locutorIdInput.getText();
        String nombre = this.locutorNombreInput.getText();
        String correo = this.locutorCorreoInput.getText();
        String telefono = this.locutorTelefonoInput.getText();
        String direccion = this.locutorDireccionInput.getText();
        String sexo = this.locutorSexoInput.getText();
        String fecha = this.locutorFechaInput.getText();

        if (id.isEmpty() || nombre.isEmpty() || correo.isEmpty()
                || telefono.isEmpty() || direccion.isEmpty() || sexo.isEmpty()
                || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos invalidos...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Locutor locutorNuevo = new Locutor(id, nombre, correo, telefono, direccion, sexo, fecha);
        if (!locutorNuevo.telefonoValido()) {
            JOptionPane.showMessageDialog(this, "Telefono invalido...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!locutorNuevo.correoValido()) {
            JOptionPane.showMessageDialog(this, "Correo invalido...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.emisora.verificarCedulaRepetida(locutorNuevo.getId())) {
            JOptionPane.showMessageDialog(this, "ID repetido...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.emisora.agregarLocutor(locutorNuevo);
        
        this.locutoresActualizarCombo.setModel(this.locutoresComboBoxModel);
        this.listaLocutoresBox.setModel(this.locutoresListModel);
        this.locutoresComboBoxModel.addElement(locutorNuevo.getId());
        this.locutoresListModel.addElement("-Nombre: " + locutorNuevo.getNombre() + "  " 
                                           +"-ID: "+ locutorNuevo.getId());
        this.locutoresProgramasComboBoxModel.addElement(id);
        
        
        this.locutorNombreInput.setText("");
        this.locutorIdInput.setText("");
        this.locutorTelefonoInput.setText("");
        this.locutorCorreoInput.setText("");
        this.locutorSexoInput.setText("");
        this.locutorDireccionInput.setText("");
        this.locutorFechaInput.setText("");
        
        JOptionPane.showMessageDialog(this, "Locutor agregado...", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonAgregarLocutorActionPerformed
    
    private void locutoresActualizarComboActionPerformed(java.awt.event.ActionEvent evt) {
    }
    
    private void programaHorarioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programaHorarioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programaHorarioInputActionPerformed

    private void programaDuracionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programaDuracionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programaDuracionInputActionPerformed
    
    private void botonCrearNuevoProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearNuevoProgramaActionPerformed
        String nombre = this.programaNombreInput.getText();
        String horario = this.programaHorarioInput.getText();
        String duracionStr = this.programaDuracionInput.getText();
        String genero = this.programasGeneroInput.getText();
        
        if(nombre.isEmpty() || horario.isEmpty() || duracionStr.isEmpty()
                || genero.isEmpty()){
            JOptionPane.showMessageDialog(this, "Datos invalidos...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int duracion = Integer.parseInt(duracionStr);
        Programa programaNuevo = new Programa(nombre, horario, duracion, genero);
        this.emisora.agregarPrograma(programaNuevo);
        
        
        this.programasListModel.addElement(programaNuevo.getNombre() + " " + programaNuevo.getGenero());
        this.programasComboBoxModel.addElement(programaNuevo.getNombre());
        
        
        
        JOptionPane.showMessageDialog(this, "Programa creado...", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonCrearNuevoProgramaActionPerformed

    private void programasListaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programasListaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programasListaComboActionPerformed
    
    /**
     * Asiga un locutor seleccionado al programa
     * @param evt 
     */
    private void botonAsignarLocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarLocutorActionPerformed
        ArrayList<Locutor> locutores;
        ArrayList<Programa> programas;

        programas = emisora.getProgramas();
        locutores = emisora.getLocutores();
        Locutor locutorAsignar;
        String locutorId = (String) locutoresProgramasComboBoxModel.getSelectedItem();
        String programaNombre = (String) this.programasComboBoxModel.getSelectedItem();
        for(Locutor locutor : locutores){
            if(locutor.getId() == locutorId){
                locutorAsignar = locutor;
                for(Programa programa : programas){
                    if(programa.getNombre() == programaNombre){
                        programa.setLocutor(locutorAsignar);
                        break;
                    }
                }
                break;
            }
        }       
        JOptionPane.showMessageDialog(this, "Se asigno correctamente el locutor...", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonAsignarLocutorActionPerformed

    private void programasLocutoresComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programasLocutoresComboActionPerformed

    }//GEN-LAST:event_programasLocutoresComboActionPerformed

    private void playlistNombreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistNombreInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playlistNombreInputActionPerformed

    private void playlistGeneroInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistGeneroInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playlistGeneroInputActionPerformed
    /** 
     * Despliega la información del locutor seleccionado para actualizarla
     * @param evt 
     */
    private void botonVerInfoLocutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerInfoLocutorActionPerformed

        String idLocutor = (String) locutoresActualizarCombo.getSelectedItem();
        Locutor locutorSeleccionado = this.emisora.obtenerPorId(idLocutor);
        
        //SE TIENE QUE CARGAR OTRA VENTANA
        InformacionLocutor ventanaInformacion = new InformacionLocutor(locutorSeleccionado, 
                this.emisora, this.locutoresListModel, this.locutoresComboBoxModel, this.locutoresProgramasComboBoxModel);
        ventanaInformacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaInformacion.setVisible(true);
    }//GEN-LAST:event_botonVerInfoLocutorActionPerformed

    private void botonVerInfoLocutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerInfoLocutorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerInfoLocutorMouseClicked

    private void programaDuracionInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programaDuracionInputKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_programaDuracionInputKeyTyped
    
    private void botonCrearDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearDiscoActionPerformed
        String nombre = this.nombreDiscoTextField.getText();
        String cantante = this.cantanteDiscoTextField.getText();
        String genero = this.generoDiscoTextField.getText();
        String anioStr = this.anioDiscoTextField.getText();
        String ubicacion = this.ubicacionDiscoTextField.getText();
        String imagen = this.imagenDiscoTextField.getText();
        

        
        if(nombre.isEmpty() || cantante.isEmpty() || genero.isEmpty() || anioStr.isEmpty() ||
                ubicacion.isEmpty() || imagen.isEmpty()){
            JOptionPane.showMessageDialog(this, "Datos incorrectos...", "ERROR", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        int anio = Integer.parseInt(anioStr);
        Disco discoNuevo = new Disco(nombre, cantante, genero, anio, ubicacion, imagen);
        
        this.emisora.agregarDisco(discoNuevo);
        this.discosListModel.addElement(discoNuevo.toString());
        this.discoComboBoxModel.addElement(discoNuevo.toString());  
    }//GEN-LAST:event_botonCrearDiscoActionPerformed

    private void anioDiscoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioDiscoTextFieldActionPerformed

    }//GEN-LAST:event_anioDiscoTextFieldActionPerformed
    /**
     * Unicamente se permite digitar numeros en el textField de año;
     * @param evt 
     */
    private void anioDiscoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioDiscoTextFieldKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_anioDiscoTextFieldKeyTyped

    /**
     * Actualizar la informacion del disco seleccionado en el comboBox
     * @param evt 
     */
    private void botonVerDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDiscoActionPerformed

        if(this.emisora.getDiscos().isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay discos creados.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String infoDisco = (String) this.discoComboBoxModel.getSelectedItem();
        String nombreDisco = "";
        for(int c = 0; c<infoDisco.length(); c++){
            if(' '== infoDisco.charAt(c)){
                break;
            }
            nombreDisco += infoDisco.charAt(c);
        }
        Disco disco = this.emisora.obtenerDisco(nombreDisco);
        InformacionDisc ventanaInformacion = new InformacionDisc(disco, this.discoComboBoxModel, this.discosListModel, this.emisora);
        
        ventanaInformacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaInformacion.setVisible(true);
    }//GEN-LAST:event_botonVerDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLocutorLabel;
    private javax.swing.JLabel actualizarLocutorLabel;
    private javax.swing.JLabel anioDiscoLabel;
    public javax.swing.JTextField anioDiscoTextField;
    private javax.swing.JButton botonAgregarLocutor;
    private javax.swing.JButton botonAgregarPlaylist;
    private javax.swing.JButton botonAsignarLocutor;
    private javax.swing.JButton botonAsignarPlaylist;
    private javax.swing.JButton botonCrearDisco;
    private javax.swing.JButton botonCrearNuevoPrograma;
    private javax.swing.JButton botonVerDisco;
    private javax.swing.JButton botonVerInfoLocutor;
    private javax.swing.JButton btnActualizarEmisora;
    private javax.swing.JPanel cancionesTab;
    private javax.swing.JLabel cantanteDiscoLabel;
    private javax.swing.JTextField cantanteDiscoTextField;
    private javax.swing.JLabel correoLocutorLabel;
    public javax.swing.JLabel direccionFisicaEmisoraShow;
    public javax.swing.JTextField direccionFisicaInput;
    private javax.swing.JLabel direccionFisicaLabel;
    private javax.swing.JLabel direccionLocutorLabel;
    private javax.swing.JLabel discoNombreLabel;
    private javax.swing.JList<String> discosListaBox;
    private javax.swing.JPanel discosTab;
    private javax.swing.JLabel fechaLocutorLabel;
    public javax.swing.JTextField frecuenciaEmisoraInput;
    public javax.swing.JLabel frecuenciaEmisoraShow;
    private javax.swing.JLabel frecuenciaLabel;
    private javax.swing.JLabel generoDiscoLabel;
    private javax.swing.JTextField generoDiscoTextField;
    private javax.swing.JLabel imagenDiscoLabel;
    private javax.swing.JTextField imagenDiscoTextField;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> listaDiscoComboBox;
    private javax.swing.JLabel listaDiscosLabel;
    private javax.swing.JList<String> listaLocutoresBox;
    private javax.swing.JLabel listaLocutoresLabel;
    private javax.swing.JLabel listaPlaylistsLabel;
    private javax.swing.JTextField locutorCorreoInput;
    private javax.swing.JTextField locutorDireccionInput;
    private javax.swing.JTextField locutorFechaInput;
    private javax.swing.JTextField locutorIdInput;
    private javax.swing.JTextField locutorNombreInput;
    private javax.swing.JTextField locutorSexoInput;
    private javax.swing.JTextField locutorTelefonoInput;
    private javax.swing.JComboBox<String> locutoresActualizarCombo;
    private javax.swing.JPanel locutoresTab;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JTextField nombreDiscoTextField;
    public javax.swing.JTextField nombreEmisoraInput;
    public javax.swing.JLabel nombreEmisoraShow;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLocutorLabel;
    private javax.swing.JLabel nuevaDireccionFisicaLabel;
    private javax.swing.JLabel nuevaFrecuenciaLabel;
    private javax.swing.JLabel nuevaPlaylistLabel;
    private javax.swing.JLabel nuevoLocutorLabel;
    private javax.swing.JLabel nuevoNombreLabel;
    private javax.swing.JLabel nuevoProgramaLabel;
    private javax.swing.JLabel nuevoUrlLabel;
    private javax.swing.JTextField playlistGeneroInput;
    private javax.swing.JLabel playlistNombre;
    private javax.swing.JTextField playlistNombreInput;
    private javax.swing.JComboBox<String> playlistsCombo;
    private javax.swing.JLabel playlistsGeneroLabel;
    private javax.swing.JList<String> playlistsListaCancionesBox;
    private javax.swing.JList<String> playlistsListaPlaylistsBox;
    private javax.swing.JPanel playlistsTab;
    private javax.swing.JLabel programaAsignarLocutorLabel;
    private javax.swing.JLabel programaAsignarPlaylistLabel;
    private javax.swing.JTextField programaDuracionInput;
    private javax.swing.JTextField programaHorarioInput;
    private javax.swing.JLabel programaHorarioLabel;
    private javax.swing.JTextField programaNombreInput;
    private javax.swing.JLabel programaNombreLabel;
    private javax.swing.JLabel programasDuracionLabel;
    private javax.swing.JTextField programasGeneroInput;
    private javax.swing.JComboBox<String> programasListaCombo;
    private javax.swing.JComboBox<String> programasListaCombo2;
    private javax.swing.JLabel programasListaLabel;
    private javax.swing.JList<String> programasListaProgramasBox;
    private javax.swing.JComboBox<String> programasLocutoresCombo;
    private javax.swing.JComboBox<String> programasPlaylistsCombo;
    private javax.swing.JPanel programasTab;
    private javax.swing.JPanel radioEmisoraTab;
    private javax.swing.JLabel sexoLocutorLabel;
    private javax.swing.JLabel telefonoLocutorLabel;
    private javax.swing.JLabel ubicacionDiscoLabel;
    private javax.swing.JTextField ubicacionDiscoTextField;
    public javax.swing.JTextField urlEmisoraInput;
    public javax.swing.JLabel urlEmisoraShow;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JLabel verCancionesPlaylistLabel;
    private javax.swing.JTabbedPane windowTabs;
    // End of variables declaration//GEN-END:variables
}
